permissions:
  contents: write
  
name: GPS Screenshot Permanent

on:
  schedule:
    - cron: "*/5 * * * *"   # IST 23:00â€“05:00
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run screenshot script
        run: node screenshot.js
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

      - name: Commit screenshots
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add screenshots/*.png
          git commit -m "Auto: GPS screenshot $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
